#!/bin/bash

#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=4:ngpus=1:mem=50gb:gpu_type=RTX6000

cd $PBS_O_WORKDIR

module load anaconda3/personal
source activate tukra-env

python main.py config.yml da-vinci -b 8 -e 200 -lr 0.0001 -w 8 \
    --save-model-to trained/da-vinci --save-model-every 10 \
    --save-results-to results/da-vinci --evaluate-every 10 \
    --home /rds/general/user/lem3617/home
